- presentation/build.gradle.kts
- presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/Library_toggleTab.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/model/Book.kt
> [Feat] library UI refactor

- presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
> [Feat] 서재 기능 구현

- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeUiState.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryUiState.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
> [Feat] 서재 기능 피드백 반영

- presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/DetailBottomSheet.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteItem.kt
> [Feat] 필사 UI 피드백 반영

- presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
- presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumAppBar.kt
- presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
- 
- 커스텀 앱바 구현 및 적용, 
- 바텀 내비 리플효과 제거 실패.. 대신 코드 정렬
<table><tr><td align="center">
</td><td align="center">
</td></tr><tr><td align="center">
</td><td align="center">
</td></tr></table>
> [Feat] 커스텀 앱바 구현

- data/src/main/java/com/hihihihi/data/remote/datasource/UserBookRemoteDataSource.kt
- data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserBookRemoteDataSourceImpl.kt
- data/src/main/java/com/hihihihi/data/repotisoryimpl/UserBookRepositoryImpl.kt
- domain/src/main/java/com/hihihihi/domain/model/ReadingStatus.kt
- domain/src/main/java/com/hihihihi/domain/model/RecordType.kt
- domain/src/main/java/com/hihihihi/domain/repository/UserBookRepository.kt
- domain/src/main/java/com/hihihihi/domain/usecase/userbook/PatchUserBookUseCase.kt
- presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumTextField.kt
- presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailFabEvent.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddQuoteDialog.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookDetailFab.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/BookSimpleInfoSection.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/SetReadingStatusBottomSheet.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/mock/Mock.kt
> [Feat] bookdetail 충돌 해결

- data/src/main/java/com/hihihihi/data/remote/datasource/HistoryRemoteDataSource.kt
- data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
- data/src/main/java/com/hihihihi/data/repotisoryimpl/HistoryRepositoryImpl.kt
- data/src/main/java/com/hihihihi/data/repotisoryimpl/UserBookRepositoryImpl.kt
- domain/src/main/java/com/hihihihi/domain/model/Statistics.kt
- domain/src/main/java/com/hihihihi/domain/repository/HistoryRepository.kt
- domain/src/main/java/com/hihihihi/domain/usecase/statistics/GetCategoryStatisticsUseCase.kt
- presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsUiState.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/CategoryCard.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/GureumStatisticsPicker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/ReadingPageCard.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/ReadingTimeCard.kt
-
- 하나의 usecase로 각 그래프 정보 얻어오도록 구현
- 장르는 확실하게 연동 상태 확인
- 그 외엔 현재 독서 기록 직접 추가가 안돼서 확인 못함
- 파이어베이스에 문서 직접 추가해봤으나 필드 오류나서 나중에 기능 추가 되었을 시 확인 예정 
- ~~통계 부분이 좀 어려워서 GPT 도움을 좀 많이 받음..~~
> [Feat] statistics 화면 파이어베이스 연동

- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
- 
- HomeView 받아오는 id 고정값 -> 현재 유저로 변경
- HomeScreen SearchTextField -> Box 로 변경하고 검색화면으로 이동하게 변경
-
> [Refactor] 홈 화면 살짝 수정

- domain/src/main/java/com/hihihihi/domain/repository/DailyReadPageRepository.kt
- domain/src/main/java/com/hihihihi/domain/usecase/statistics/GetCategoryStatisticsUseCase.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsViewModel.kt
- 
- 통계 계산 안되던 로직 변경
-  최초 호출 Screen에서 Viewmodel로 변경
-
> [Refactor] 통계 계산 안되던 로직 변경, 최초 호출 Screen에서 Viewmodel로 변경

- data/src/main/java/com/hihihihi/data/remote/datasource/UserRemoteDataSource.kt
- data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
- data/src/main/java/com/hihihihi/data/remote/datasourceimpl/UserRemoteDataSourceImpl.kt
- data/src/main/java/com/hihihihi/data/repotisoryimpl/UserRepositoryImpl.kt
- domain/src/main/java/com/hihihihi/domain/repository/UserRepository.kt
- domain/src/main/java/com/hihihihi/domain/usecase/user/GetHomeDataUseCase.kt
- domain/src/main/java/com/hihihihi/domain/usecase/user/UpdateDailyGoalTimeUseCase.kt
- presentation/src/main/java/com/hihihihi/gureumpage/di/UseCaseModule.kt
- presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/component/BookItem.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/QuotesViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/DetailBottomSheet.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/quotes/component/QuoteContent.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
- 
- UI 적으로 맞지 않던 부분(컬러, 패딩) 수정
- 서재 -> 책 상세 구현 안되어있던 부분 구현
- 고정 id 값으로 불러오던 부분 로그인된 유저 id로 수정 (필사, 서재)
-
> [Refactor] 자잘한 부분 리팩토링

- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/SearchBarWithBackground.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/library/LibraryScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/components/CategoryCard.kt
- presentation/src/main/res/drawable/ic_library_finished.xml
- presentation/src/main/res/drawable/ic_library_planned.xml
- 
- 서재에 페이저 적용
- 일부 컴포넌트 리플효과 제거
-
https://github.com/user-attachments/assets/f938cf16-7ae7-453a-a4b8-6602d48cb495
> [Refactor] 서재 1차 리팩터링

- presentation/src/main/java/com/hihihihi/gureumpage/common/utils/Formatters.kt
- presentation/src/main/java/com/hihihihi/gureumpage/designsystem/components/GureumTextField.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddQuoteDialog.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/ReadingProgressSection.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/SetReadingStatusBottomSheet.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/tabs/QuotesTab.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/GureumNumberPicker.kt
- 
- 바텀시트 및 다이알로그의 버그들 수정
- 상태에 따라 화면에 보이는 아이템 다르게 수정
-
> [Feat] 서재 2차 리팩토링

- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/search/component/AddBookBottomSheet.kt
- 
- 텍스트 필드를 모두 비우면 앱이 튕기던 현상 수정
-
> [HOTFIX] 텍스트 필드를 모두 비우면 앱이 튕기던 현상 수정

- data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/component/TimerRing.kt
- 
- 아이콘 및 글씨 크기, 색상
- addHistory 날라간 코드 복구
-
> [Refactor] 타이머 리팩토링

- data/src/main/java/com/hihihihi/data/remote/datasource/HistoryRemoteDataSource.kt
- data/src/main/java/com/hihihihi/data/remote/datasourceimpl/HistoryRemoteDataSourceImpl.kt
- data/src/main/java/com/hihihihi/data/repotisoryimpl/HistoryRepositoryImpl.kt
- domain/src/main/java/com/hihihihi/domain/repository/HistoryRepository.kt
- domain/src/main/java/com/hihihihi/domain/usecase/history/AddHistoryUseCase.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/BookDetailViewModel.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/bookdetail/components/AddManualHistoryDialog.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/timer/TimerViewModel.kt
- startPage 와 endPage 차이를 현재 current에 더했더니 totalPage를 넘는 버그 수정
- 
- 
-
> [Fix] 독서 기록 추가 후 현재 페이지 업데이트 버그 수정

- presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/HomeScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/search/SearchScreen.kt
- presentation/src/main/res/values/themes.xml
> [Fix] 상태바 컬러 오류 수정

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/hihihihi/gureumpage/GureumApp.kt
- presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
- presentation/src/main/java/com/hihihihi/gureumpage/di/NotificationModule.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/DailyReminderWorker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/common/Channels.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/common/GureumMessagingService.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/common/NotificationFactory.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/schema/PushPayload.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/Picker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
- 
- 리마인더 알림 기능 구현
- 어제 올린 줄 알았는데 아니네 ㅎㅎ;;
- 마이페이지 알림 시간 설정이나 온오프 추가 필요
> [Feat] 리마인더 알림 기능 구현

- presentation/src/main/java/com/hihihihi/gureumpage/ui/onboarding/OnBoardingScreen.kt
- 
- 다음 화면으로 넘어갈 때 무조건 닉네임을 저장하도록 구현
- 일단 급한 불 끈 것이라 추후 코드 리팩터링 필요
> [Hotfix] 온보딩 화면 닉네임 저장 로직 수정

- presentation/src/main/java/com/hihihihi/gureumpage/widgets/reading/CurrentReadingBooksWidget.kt
- presentation/src/main/res/xml/current_reading_book_widget_info.xml
- presentation/src/main/res/xml/current_reading_books_widget_info.xml
> [Refactor] 위젯 ui 업데이트

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/hihihihi/gureumpage/MainActivity.kt
- presentation/src/main/java/com/hihihihi/gureumpage/di/SummaryModule.kt
- presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumBottomNavigationBar.kt
- presentation/src/main/java/com/hihihihi/gureumpage/navigation/GureumNavGraph.kt
- presentation/src/main/java/com/hihihihi/gureumpage/navigation/NavigationRoute.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/common/GureumMessagingService.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/common/NotificationFactory.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/progress/DailyGoalNotifier.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/progress/Goal80ReminderScheduler.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/progress/Goal80ReminderWorker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/reminder/DailyReminderWorker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/reminder/ReminderScheduler.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/MonthlySummaryWorker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/SummaryProvider.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/SummaryProviderImpl.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/SummaryScheduler.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/WeeklySummaryWorker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/notification/summary/YearlySummaryWorker.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/home/components/ReadingGoalSection.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/splash/SplashScreen.kt
- presentation/src/main/java/com/hihihihi/gureumpage/ui/statistics/StatisticsScreen.kt
- 
- 일일 목표 진행도 알림 구현
- 주간, 월간, 연간 요약 알림 구현
- 테스트 완료
-
> [Feat] 앱 알림 구현
